### ISSUE TITLE
Range Object

### ISSUE THREAD

**Issue by mjardeli** [GoSecure/Cisco2Checkpoint#11]
Hi Martin,

How are you? Hope you are well.

I am trying to parse a range object:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
object network network_object
 range 192.168.1.150 192.168.1.160
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
root@splunk:~/c2c# python2.7 c2c.py --verify --format text --ciscoFile 'test' --syntax asa --policy My_Policy --installOn My_Firewall --output 'network_script_verify.txt'
 Importing all objects except groups.
 Importing Checkpoint network objects
 Importing all names.
 Importing all hosts.
 Importing all networks.
 Importing all ranges.
Traceback (most recent call last):
  File "c2c.py", line 168, in <module>
    c2c.importConfig(args.cpPortsFile,args.cpNetObjFile,args.ciscoFile)
  File "lib/cisco2checkpoint.py", line 1740, in importConfig
    self._importRanges(self.parser.getRangeObjs())
  File "lib/cisco2checkpoint.py", line 1800, in _importRanges
    print_debug('  Importing: %r' % h)
NameError: global name 'h' is not defined
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Is it normal ?

thanks,

**Comment by martindube** [comment]
It was a typo! Thanks for sending an issue. You can git pull.

**Comment by mjardeli** [comment]
Hi Martin,

Thanks for looking! Received a different error now:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "c2c.py", line 168, in <module>
    c2c.importConfig(args.cpPortsFile,args.cpNetObjFile,args.ciscoFile)
  File "lib/cisco2checkpoint.py", line 1740, in importConfig
    self._importRanges(self.parser.getRangeObjs())
  File "lib/cisco2checkpoint.py", line 1801, in _importRanges
    self.addObj(CiscoRange(self, r, color=self.color))
  File "lib/cisco2checkpoint.py", line 670, in __init__
    if portObj != None:
NameError: global name 'portObj' is not defined
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by martindube** [comment]
Weird that I have never hit this one. It should work now.

**Comment by mjardeli** [comment]
Perfect! working thank you... :)
