### ISSUE TITLE
Migration tool for R80 - SmartMove

### ISSUE THREAD

**Issue by mjardeli** [GoSecure/Cisco2Checkpoint#17]
Hi Martin,

The last issues I spotted I was actually "cheating", I was using an internal checkpoint tool to compare with your results. Then trying to improve your script.

The good news this tool is now open to all public, bad news is it will produce code to R80.10 ( with security zones concept). Yes R80.10 is now GA as well.

Link to the open tool:
https://github.com/CheckPoint-APIs-Team/SmartMove

CheckPoint sk to download tool:
https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk115416&partition=Advanced&product=Security

R80.10 CheckPoint SK:
https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk111841 

kind regards,

**Comment by DoZ10** [comment]
Is that me or Checkpoint is trying to get credit for your great hard work on your OWN REPOSITORY ? 

#wtf #shame

**Comment by martindube** [comment]
Hi mjardeli,

Thanks for sharing, @mjardeli. It might be useful for people looking to migrate to R80.
