### ISSUE TITLE
Possible Module name error 

### ISSUE THREAD

**Issue by Sraza11** [GoSecure/Cisco2Checkpoint#2]
File "C:\Users\xx\Desktop\Py\Cisco2Checkpoint-master\c2c.py", line 34, in <module>
    from cisco2checkpoint import Cisco2Checkpoint,Cisco2CheckpointManager
  File "lib\cisco2checkpoint.py", line 26, in <module>
    from ciscoconfparse import ciscoconfparse
ImportError: No module named **ciscoconfparse**

**Comment by martindube** [comment]
Did you use `git clone --recursive` ?

**Comment by Sraza11** [comment]
I downloaded directly to my computer as zip and then downloaded the ciscoconfparse module.

**Comment by martindube** [comment]
If you put ciscoconfparse in the `lib` or root folder of the project, the import should work. Try a `git clone --recursive` as in the README.md if it doesn't work.

**Comment by Sraza11** [comment]
i tried git clone -recursive... now getting following error

 File "lib\ciscoconfparse\ciscoconfparse\ciscoconfparse.py", line 3, in <module>
    from colorama import Fore, Back, Style
ImportError: No module named colorama

**Comment by martindube** [comment]
You are right, ciscoconfparse require 3 packages. You could download them using:

`pip2 install ipaddr dnspython colorama`

or by installing ciscoconfparse

```
cd lib/ciscoconfparse
python2 ./setup.py install
```

**Comment by Sraza11** [comment]
missing module error is resolved.   now when i run the following command 

```
python27 c2c.py --export \
    --ciscoFile 'some_cisco_conf.txt' \
    --syntax asa \
    --policy My_Policy \
    --installOn My_Firewall \
    --output 'network_script.txt' \
```
it is not working...

**Comment by martindube** [comment]
I am happy to see that the dependencies are fixed. To help you, I need more details about the issue. 

Also, I see here that this is an example from the README. Please take time to fill the fields with your needs.
