### ISSUE TITLE
cisco asa: maybe critical bug with protocol

### ISSUE THREAD

**Issue by mjardeli** [GoSecure/Cisco2Checkpoint#5]
Hi,

Am I missing anything here? config line with https is being recognized as http.

thanks in advance,

[service_https.txt](https://github.com/GoSecure/Cisco2Checkpoint/files/946998/service_https.txt)

**Comment by martindube** [comment]
Hi mjardeli,

Port 80 is added because of `port-object eq www`

From what I know, it is the desired behavior on IOS. Could it be a different behavior between IOS and ASA?

**Comment by mjardeli** [comment]
Hi martindube,

Did you test it on your environment?

For the config line:
object-group service groupservice tcp
 port-object eq 443
 port-object eq https
 port-object eq www
 service-object tcp eq https

Which have 4 protocols definitions 2 for http and 2 for https, app is recognizing https only with tcp eq 443. tcp port 80 ( http) should be recognized only for the third line, here follow the parse verifier:

CiscoServiceGroup(name=groupservice,desc=,nbMembers=4)
 CiscoServicePort(name=https,port=443,desc=HTTP protocol over TLS/SSL,alias=)
 CiscoServicePort(name=http,port=80,desc=Hypertext Transfer Protocol,alias=)
 CiscoServicePort(name=http,port=80,desc=Hypertext Transfer Protocol,alias=)
 CiscoServicePort(name=http,port=80,desc=Hypertext Transfer Protocol,alias=)
 Verify: <ASAObjGroupService # 0 'groupservice'>

Note it is recognizing as http for second and fourth lines.

I tried putting only one line "port-object eq https" and still recognizing as http instead of https.

regards,

**Comment by martindube** [comment]
I found it ! 

It was a bug in an enormous regular expression. http was before https in a list of port names so it was always matched first.

I pushed the change in `master`. Please git pull.

**Comment by mjardeli** [comment]
Cheers! This was my guess as well, definition of http before the https.

Please be aware this can happen with similar protocols like smtp and smtps etc. Or protocols that start with same protocol name, if the shortest one come first the second will not be matched. Suggestion list protocol names and sort them searching for similar one.

Are you using last version of ciscoconfparse? 1.2.47? Can I use last one or better to stick to the version you provide?

kind regards,

**Comment by martindube** [comment]
Good idea. I will work on it when I have more time.

For ciscoconfparse, we need to stick to the version I provide for now because the project is very sensitive to changes in the parsers. That being said, you can give it a try :)

Thanks again for submitting the issue.

**Comment by mjardeli** [comment]
Hi Mart,

Config line is now being recognized and loaded. But seems there is something wrong with the logic. 

When I try to add it to the checkpoint, its giving me the following error:
~~~~~~~~~~~~~~~~~~~~~~~~~~
dbedit -local -f network_script.txt -ignore_script_failure -continue_updating
H_1.1.1.254 updated successfully.
Object H_1.1.1.254 already exists
Object Already Exists
Error in line: 12
exampleobject updated successfully.
groupexample updated successfully.
network_objects::H_1.1.1.254 Object H_1.1.1.254 already exists
Object Already Exists for network_objects::H_1.1.1.254
Error in line: 25

network_objects::H_1.1.1.254 was not updated. update now ?[y/n] y
~~~~~~~~~~~~~~~~~~~~~~~~~~
I am using R77.30, seems it is trying to add host twice, harmless error by the way.

Using your verify command, I receive the following output:

CiscoNetGroup(name=exampleobject,desc=,nbMembers=1,alias=)
 CiscoHost(name=H_1.1.1.254,ipAddr=1.1.1.254,desc=,alias=)
 Verify: <ASAObjGroupNetwork # 1 'object-group network exampleobject'>
CiscoNetGroup(name=groupexample,desc=,nbMembers=1,alias=)
 CiscoNetGroup(name=exampleobject,desc=,nbMembers=1,alias=)
   CiscoHost(name=H_1.1.1.254,ipAddr=1.1.1.254,desc=,alias=)
 Verify: <ASAObjGroupNetwork # 4 'object-group network groupexample'>

I did this on a big config file, normally I look for the " Verify:" tag as it indicates an issue. 

Am i correct thinking in this way? If yes, why is it flagged to " Verify:"?

thank you very much,

**Comment by mjardeli** [comment]
Hi Martin,

Please allow me to contribute, I am not a big python programmer but ...

I am not sure this is related to your program or ciscoconfparse, I found reference on both, maybe its the case to ask ciscoconfparse to update their side as well as those are critical.

I added smtps (tcp 465) to the PORT_DIC on config.py and protocol_values.py

I changed _PORT_NAMES order, for the following ports: ftp, ftp-data, ldap, ldaps and smtps for the same reason you found before.

_PORT_NAMES = r'aol|bgp|chargen|cifs|citrix-ica|cmd|ctiqbe|daytime'\
                '|discard|domain|echo|exec|finger|tftp|ftp-data|ftp|gopher'\
                '|h323|hostname|https|http|ident|imap4|irc|kerberos|klogin'\
                '|kshell|ldaps|ldap|login|lotusnotes|lpd|netbios-ssn|nfs'\
                '|nntp|ntp|pcanywhere-data|pim-auto-rp|pop2|pop3|pptp|rsh'\
                '|rtsp|sip|smtps|smtp|sqlnet|ssh|sunrpc|tacacs|talk|telnet|uucp'\
                '|whois|www|netbios-ns|netbios-dgm|netbios-ss|snmptrap|snmp'\
                '|syslog|isakmp|bootps|bootpc|radius|\d+'

I tested here smtps and its translating to tcp 465 correctly after those changes I mentioned.

kind regards,

**Comment by mjardeli** [comment]
Hi Martin,

Please allow me to contribute, I am not a big python programmer but ...

I am not sure this is related to your program or ciscoconfparse, I found reference on both, maybe its the case to ask ciscoconfparse to update their side as well as those are critical.

I added smtps (tcp 465) to the PORT_DIC on config.py and protocol_values.py

I changed _PORT_NAMES order, for the following ports: ftp, ftp-data, ldap, ldaps and smtps for the same reason you found before.

_PORT_NAMES = r'aol|bgp|chargen|cifs|citrix-ica|cmd|ctiqbe|daytime'\
                '|discard|domain|echo|exec|finger|tftp|ftp-data|ftp|gopher'\
                '|h323|hostname|https|http|ident|imap4|irc|kerberos|klogin'\
                '|kshell|ldaps|ldap|login|lotusnotes|lpd|netbios-ssn|nfs'\
                '|nntp|ntp|pcanywhere-data|pim-auto-rp|pop2|pop3|pptp|rsh'\
                '|rtsp|sip|smtps|smtp|sqlnet|ssh|sunrpc|tacacs|talk|telnet|uucp'\
                '|whois|www|netbios-ns|netbios-dgm|netbios-ss|snmptrap|snmp'\
                '|syslog|isakmp|bootps|bootpc|radius|\d+'

I tested here smtps and its translating to tcp 465 correctly after those changes I mentioned.

kind regards,

**Comment by martindube** [comment]
I updated the code with _PORT_NAMES and and PORT_DIC. I will push soon. Don't hesitate to send a pull request next time. It's a good way to save time and keep a tracking of what's changed.

Looking at ciscoconfparse code , I think that I should replace PROTO_DIC and PORT_DIC (from `config.py`) to ASA_IP_PROTOCOLS and ASA_TCP_PORTS. I just need to make sure that they are the same for IOS first.

Thanks,
